# Generated by Django 5.0 on 2024-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_to_business_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('seller', models.TextField(null=True)),
            ],
        ),
    ]
