# Generated by Django 5.0 on 2024-04-30 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_alter_d_original_productsmodel_rating_and_more'),
        ('mio_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_to_business_payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product_ordermodel'),
        ),
    ]
