# Generated by Django 5.0 on 2024-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0002_business_commision'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(null=True)),
                ('banner', models.JSONField(null=True)),
                ('ad', models.JSONField(null=True)),
            ],
        ),
    ]
