# Generated by Django 5.0 on 2024-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0002_admin_to_business_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_to_business_payment',
            name='balance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='admin_to_business_payment',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
