# Generated by Django 5.0 on 2024-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0004_remove_banner_ad_remove_banner_banner_banner_ad1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.TextField(null=True)),
                ('pincode', models.JSONField(null=True)),
            ],
        ),
    ]
