# Generated by Django 5.0 on 2024-04-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0008_admin_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_user',
        ),
    ]
