# Generated by Django 5.0 on 2024-04-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0010_admin_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_login',
        ),
    ]
