# Generated by Django 5.0 on 2024-04-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0014_alter_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_do_something', 'Can do something with this model')]},
        ),
    ]
