# Generated by Django 5.0 on 2024-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0015_alter_customuser_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
