# Generated by Django 5.0 on 2024-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0016_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='shutdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping', models.BooleanField(default=0, null=True)),
                ('food', models.BooleanField(default=0, null=True)),
                ('fresh_cuts', models.BooleanField(default=0, null=True)),
                ('daily_mio', models.BooleanField(default=0, null=True)),
                ('pharmacy', models.BooleanField(default=0, null=True)),
                ('d_original', models.BooleanField(default=0, null=True)),
                ('jewellery', models.BooleanField(default=0, null=True)),
            ],
        ),
    ]
