# Generated by Django 5.0 on 2024-04-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0017_shutdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(null=True)),
                ('phonenumber', models.TextField(null=True)),
                ('access_priveleges', models.JSONField(null=True)),
            ],
        ),
    ]
