# Generated by Django 5.0 on 2024-04-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0018_admin_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub_CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(null=True)),
                ('phonenumber', models.TextField(null=True)),
                ('hub', models.TextField(null=True)),
                ('door_no', models.TextField(null=True)),
                ('street', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
            ],
        ),
    ]
