# Generated by Django 4.0.4 on 2024-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mio_admin', '0019_hub_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission_editing',
            name='normal_delivery_commision',
            field=models.IntegerField(null=True),
        ),
    ]
