# Generated by Django 4.2.5 on 2024-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Businessmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField()),
                ('password', models.TextField()),
                ('otp', models.IntegerField()),
                ('user_otp', models.IntegerField()),
                ('adhar_number', models.TextField()),
                ('full_name', models.TextField()),
            ],
        ),
    ]
