# Generated by Django 4.2.5 on 2024-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_businessmodel_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='user_otp',
        ),
    ]
