# Generated by Django 4.2.5 on 2024-02-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_businessmodel_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='adhar_number',
        ),
        migrations.RemoveField(
            model_name='businessmodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='aadhar_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='businessmodel',
            name='phone_number',
            field=models.TextField(null=True),
        ),
    ]
