# Generated by Django 4.2.5 on 2024-02-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_businessmodel_adhar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='user_otp',
        ),
    ]
