# Generated by Django 4.2.5 on 2024-02-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_businessmodel_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='user_otp',
            field=models.IntegerField(null=True),
        ),
    ]
