# Generated by Django 4.2.5 on 2024-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_d_originalmodel_dailymio_model_foodmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalmodel',
            name='d_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dailymio_model',
            name='fresh_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='food_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='freshcutsmodel',
            name='fresh_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='jewel_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_model',
            name='pharm_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoppingmodel',
            name='shop_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='used_produtsmodel',
            name='used_id',
            field=models.TextField(null=True),
        ),
    ]
