# Generated by Django 4.2.5 on 2024-02-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_dailymio_model_fresh_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_originalmodel',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='dailymio_model',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='freshcutsmodel',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='jewellerymodel',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='pharmacy_model',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='shoppingmodel',
            name='pickup_location',
        ),
    ]
