# Generated by Django 4.2.5 on 2024-02-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_area_shoppingmodel_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d_originalmodel',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='dailymio_model',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='foodmodel',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='freshcutsmodel',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='jewellerymodel',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='pharmacy_model',
            old_name='Area',
            new_name='area',
        ),
    ]
