# Generated by Django 4.2.5 on 2024-02-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_area_d_originalmodel_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('shop_id', models.TextField(null=True)),
            ],
        ),
    ]
