# Generated by Django 4.2.5 on 2024-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_shop_productmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('dmio_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='doriginal_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('d_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.TextField(null=True)),
                ('shop_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='freshcut_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fresh_id', models.TextField(null=True)),
                ('shop_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jewel_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewel_id', models.TextField(null=True)),
                ('shop_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('pharm_id', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usedpro_productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('used_id', models.TextField(null=True)),
            ],
        ),
    ]
