# Generated by Django 4.2.5 on 2024-02-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_daily_productmodel_doriginal_productmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_productmodel',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='freshcut_productmodel',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='jewel_productmodel',
            name='shop_id',
        ),
    ]
