# Generated by Django 4.2.5 on 2024-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_food_productmodel_shop_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_productmodel',
            name='product_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='freshcut_productmodel',
            name='product_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_productmodel',
            name='product_id',
            field=models.TextField(null=True),
        ),
    ]
