# Generated by Django 4.2.5 on 2024-02-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_food_productmodel_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_productmodel',
        ),
        migrations.DeleteModel(
            name='doriginal_productmodel',
        ),
        migrations.DeleteModel(
            name='food_productmodel',
        ),
        migrations.DeleteModel(
            name='freshcut_productmodel',
        ),
        migrations.DeleteModel(
            name='jewel_productmodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_productmodel',
        ),
        migrations.DeleteModel(
            name='shop_productmodel',
        ),
        migrations.DeleteModel(
            name='usedpro_productmodel',
        ),
    ]
