# Generated by Django 4.2.5 on 2024-02-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_d_originalproductsmodel_dmio_dairymodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fresh_meatmasalasmodel',
        ),
    ]
