# Generated by Django 4.2.5 on 2024-02-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_delete_fresh_meatmasalasmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='fresh_meatmasalamodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('fresh_id', models.TextField(null=True)),
            ],
        ),
    ]
