# Generated by Django 4.2.5 on 2024-02-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_fresh_meatmasalamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessmodel',
            name='aadhar_number',
        ),
    ]
