# Generated by Django 4.2.5 on 2024-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_used_bikescootersmodel_delete_used_carsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailymio_model',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='freshcutsmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_model',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='shoppingmodel',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
