# Generated by Django 4.2.5 on 2024-02-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_d_originalmodel_status_dailymio_model_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_originalmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dailymio_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='freshcutsmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jewellerymodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pharmacy_model',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shoppingmodel',
            name='status',
        ),
    ]
