# Generated by Django 4.2.5 on 2024-02-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_ordermodel_d_id_remove_ordermodel_dmio_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='d_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='dmio_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='food_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fresh_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='jewel_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='pharm_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shop_id',
            field=models.TextField(null=True),
        ),
    ]
