# Generated by Django 4.2.5 on 2024-03-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_end_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
    ]
