# Generated by Django 4.2.5 on 2024-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_businessmodel_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='business_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_amount',
            field=models.TextField(null=True),
        ),
    ]
