# Generated by Django 4.2.5 on 2024-03-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_ordermodel_business_id_ordermodel_product_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ordermodel',
        ),
    ]
