# Generated by Django 4.2.5 on 2024-03-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_shop_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='e_user_id',
            field=models.TextField(null=True),
        ),
    ]
