# Generated by Django 4.2.5 on 2024-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_shop_ordermodel_e_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
