# Generated by Django 4.2.5 on 2024-03-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_shop_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
    ]
