# Generated by Django 4.2.5 on 2024-03-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_shop_ordermodel_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='monthly_revenue',
        ),
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='total_revenue',
        ),
    ]
