# Generated by Django 4.2.5 on 2024-03-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_shop_ordermodel_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingmodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoppingmodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
    ]
