# Generated by Django 4.2.5 on 2024-03-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_shoppingmodel_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalmodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='d_originalmodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dailymio_model',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dailymio_model',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='freshcutsmodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='freshcutsmodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_model',
            name='monthly_revenue',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_model',
            name='total_revenue',
            field=models.TextField(null=True),
        ),
    ]
