# Generated by Django 4.2.5 on 2024-03-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_d_originalmodel_monthly_revenue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('dmio_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dorigin_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('d_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('food_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fresh_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('fresh_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jewel_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('jewel_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('business_id', models.TextField(null=True)),
                ('pharm_id', models.TextField(null=True)),
                ('product_id', models.TextField(null=True)),
                ('e_user_id', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
            ],
        ),
    ]
