# Generated by Django 4.2.5 on 2024-03-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_daily_ordermodel_dorigin_ordermodel_food_ordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
