# Generated by Django 4.2.5 on 2024-03-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_shop_ordermodel_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_usermodel',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='user_otp',
            field=models.IntegerField(null=True),
        ),
    ]
