# Generated by Django 4.0.4 on 2024-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_end_usermodel_otp_end_usermodel_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
    ]
