# Generated by Django 4.0.4 on 2024-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_daily_ordermodel_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='payment_status',
            field=models.TextField(null=True),
        ),
    ]
