# Generated by Django 4.0.4 on 2024-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_daily_ordermodel_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_originalmodel',
            name='region',
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='hub',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoppingmodel',
            name='hub',
            field=models.TextField(null=True),
        ),
    ]
