# Generated by Django 4.0.4 on 2024-03-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_d_originalmodel_region_jewellerymodel_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalmodel',
            name='hub',
            field=models.TextField(null=True),
        ),
    ]
