# Generated by Django 4.0.4 on 2024-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_d_originalmodel_hub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(null=True)),
                ('password', models.TextField()),
                ('full_name', models.TextField()),
                ('created_date', models.TextField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('user_otp', models.IntegerField(null=True)),
                ('profile_picture', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='food_bakerymodel',
            name='bakery',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_beefmodel',
            name='beef',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_biriyanimodel',
            name='biriyani',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_burgermodel',
            name='burger',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_cakemodel',
            name='cake',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_chickenbiriyanimodel',
            name='chicken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_chinesemodel',
            name='chinese',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_firedchickenmodel',
            name='fired',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_icecreammodel',
            name='icecream',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_mealsmodel',
            name='meals',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_pizzamodel',
            name='pizza',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_teacoffemodel',
            name='tea',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_tiffenmodel',
            name='tiffen',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_beefmodel',
            name='beef',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_chickenmodel',
            name='chicken',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_muttonmodel',
            name='mutton',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_goldmodel',
            name='gold',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_silvermodel',
            name='silver',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_appliancesmodel',
            name='appl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_autoaccessoriesmodel',
            name='auto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_booksmodel',
            name='book',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_electronicsmodel',
            name='elect',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_fashionmodel',
            name='fas',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_furnituremodel',
            name='fur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_groceriesmodel',
            name='groc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_healthcaremodel',
            name='health',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_kitchenmodel',
            name='kit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_mobilemodel',
            name='mob',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_personalcaremodel',
            name='pers',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_petsuppliesmodel',
            name='pets',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_sportsmodel',
            name='sport',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_toysmodel',
            name='toys',
            field=models.TextField(null=True),
        ),
    ]
