# Generated by Django 4.0.4 on 2024-03-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_delivery_model_food_bakerymodel_bakery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalproductsmodel',
            name='d_original',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_dairymodel',
            name='dairy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_eggsmodel',
            name='eggs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_fishmodel',
            name='fish',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_fruitsmodel',
            name='fruits',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_grocerymodel',
            name='grocery',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_meatmodel',
            name='meat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_vegitablesmodel',
            name='veg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_choppedvegmodel',
            name='chopp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_combomodel',
            name='combo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_dryfishmodel',
            name='dry',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_eggmodel',
            name='egg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_fishseafoodmodel',
            name='fish',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_meatmasalamodel',
            name='meat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_pondfishmodel',
            name='pond',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_prawnsmodel',
            name='prawns',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_allopathicmodel',
            name='allo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_ayurvedicmodel',
            name='ayur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_herbaldrinksmodel',
            name='herbal',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_siddhamodel',
            name='siddha',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_unanimodel',
            name='unani',
            field=models.TextField(null=True),
        ),
    ]
