# Generated by Django 4.2.5 on 2024-03-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_d_originalproductsmodel_d_original_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_model',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='delivery_model',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='delivery_model',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='delivery_model',
            name='password',
        ),
        migrations.RemoveField(
            model_name='delivery_model',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='delivery_model',
            name='user_otp',
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='aadhar_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='aadhar_pic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='acc_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='bank_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='bank_passbok_pic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='delivery_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='driving_licensenum',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='drlicence_pic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='ifsc_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='name_asper_passbook',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='pan_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='pan_pic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='wp_number',
            field=models.TextField(null=True),
        ),
    ]
