# Generated by Django 4.2.5 on 2024-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_remove_delivery_model_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
