# Generated by Django 4.2.5 on 2024-03-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_delivery_model_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='approve_status',
            field=models.TextField(null=True),
        ),
    ]
