# Generated by Django 4.2.5 on 2024-03-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_delivery_model_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='today_earnings',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='earn_perkm_amount',
            field=models.TextField(null=True),
        ),
    ]
