# Generated by Django 4.2.5 on 2024-03-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_delivery_model_today_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='delivery_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
    ]
