# Generated by Django 4.0.4 on 2024-03-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_shop_ordermodel_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='daily_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='dorigin_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='dorigin_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='food_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='food_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='fresh_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='fresh_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='jewel_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='jewel_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_ordermodel',
            name='e_user_id',
        ),
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='delivery_id',
        ),
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='e_user_id',
        ),
    ]
