# Generated by Django 4.0.4 on 2024-03-30 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_daily_ordermodel_business_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='earn_perkm_amount',
        ),
        migrations.AddField(
            model_name='daily_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='daily_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='daily_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='daily_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dorigin_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businessmodel'),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
        migrations.AddField(
            model_name='shop_ordermodel',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
    ]
