# Generated by Django 4.0.4 on 2024-04-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_shop_ordermodel_earn_perkm_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shop_electronicsmodel',
        ),
    ]
