# Generated by Django 4.0.4 on 2024-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_delete_shop_electronicsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('shop_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jewel_ordermodel',
            name='delivery',
        ),
    ]
