# Generated by Django 4.0.4 on 2024-04-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_shop_productsmodel_remove_jewel_ordermodel_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='delivery',
        ),
    ]
