# Generated by Django 4.0.4 on 2024-04-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_shop_ordermodel_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='shop_ordermodel',
            name='product_id',
        ),
    ]
