# Generated by Django 4.0.4 on 2024-04-02 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_remove_shop_ordermodel_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_ordermodel',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel'),
        ),
    ]
