# Generated by Django 4.0.4 on 2024-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_shop_ordermodel_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_original_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('d_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dmio_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('dmio_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='food_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('food_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fresh_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('fresh_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jewel_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('jewel_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pharmacy_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('pharm_id', models.TextField(null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='d_originalproductsmodel',
        ),
        migrations.DeleteModel(
            name='dmio_dairymodel',
        ),
        migrations.DeleteModel(
            name='dmio_eggsmodel',
        ),
        migrations.DeleteModel(
            name='dmio_fishmodel',
        ),
        migrations.DeleteModel(
            name='dmio_fruitsmodel',
        ),
        migrations.DeleteModel(
            name='dmio_grocerymodel',
        ),
        migrations.DeleteModel(
            name='dmio_meatmodel',
        ),
        migrations.DeleteModel(
            name='dmio_vegitablesmodel',
        ),
        migrations.DeleteModel(
            name='food_bakerymodel',
        ),
        migrations.DeleteModel(
            name='food_beefmodel',
        ),
        migrations.DeleteModel(
            name='food_biriyanimodel',
        ),
        migrations.DeleteModel(
            name='food_burgermodel',
        ),
        migrations.DeleteModel(
            name='food_cakemodel',
        ),
        migrations.DeleteModel(
            name='food_chickenbiriyanimodel',
        ),
        migrations.DeleteModel(
            name='food_chinesemodel',
        ),
        migrations.DeleteModel(
            name='food_firedchickenmodel',
        ),
        migrations.DeleteModel(
            name='food_icecreammodel',
        ),
        migrations.DeleteModel(
            name='food_mealsmodel',
        ),
        migrations.DeleteModel(
            name='food_pizzamodel',
        ),
        migrations.DeleteModel(
            name='food_teacoffemodel',
        ),
        migrations.DeleteModel(
            name='food_tiffenmodel',
        ),
        migrations.DeleteModel(
            name='fresh_beefmodel',
        ),
        migrations.DeleteModel(
            name='fresh_chickenmodel',
        ),
        migrations.DeleteModel(
            name='fresh_choppedvegmodel',
        ),
        migrations.DeleteModel(
            name='fresh_combomodel',
        ),
        migrations.DeleteModel(
            name='fresh_dryfishmodel',
        ),
        migrations.DeleteModel(
            name='fresh_eggmodel',
        ),
        migrations.DeleteModel(
            name='fresh_fishseafoodmodel',
        ),
        migrations.DeleteModel(
            name='fresh_meatmasalamodel',
        ),
        migrations.DeleteModel(
            name='fresh_muttonmodel',
        ),
        migrations.DeleteModel(
            name='fresh_pondfishmodel',
        ),
        migrations.DeleteModel(
            name='fresh_prawnsmodel',
        ),
        migrations.DeleteModel(
            name='jewel_goldmodel',
        ),
        migrations.DeleteModel(
            name='jewel_silvermodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_allopathicmodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_ayurvedicmodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_herbaldrinksmodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_siddhamodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_unanimodel',
        ),
        migrations.DeleteModel(
            name='shop_appliancesmodel',
        ),
        migrations.DeleteModel(
            name='shop_autoaccessoriesmodel',
        ),
        migrations.DeleteModel(
            name='shop_booksmodel',
        ),
        migrations.DeleteModel(
            name='shop_fashionmodel',
        ),
        migrations.DeleteModel(
            name='shop_furnituremodel',
        ),
        migrations.DeleteModel(
            name='shop_groceriesmodel',
        ),
        migrations.DeleteModel(
            name='shop_healthcaremodel',
        ),
        migrations.DeleteModel(
            name='shop_kitchenmodel',
        ),
        migrations.DeleteModel(
            name='shop_mobilemodel',
        ),
        migrations.DeleteModel(
            name='shop_personalcaremodel',
        ),
        migrations.DeleteModel(
            name='shop_petsuppliesmodel',
        ),
        migrations.DeleteModel(
            name='shop_sportsmodel',
        ),
        migrations.DeleteModel(
            name='shop_toysmodel',
        ),
    ]
