# Generated by Django 4.0.4 on 2024-04-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_d_original_productsmodel_dmio_productsmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dorigin_ordermodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='dorigin_ordermodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='dorigin_ordermodel',
            name='e_user',
        ),
        migrations.RemoveField(
            model_name='food_ordermodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='food_ordermodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='food_ordermodel',
            name='e_user',
        ),
        migrations.RemoveField(
            model_name='fresh_ordermodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='fresh_ordermodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='fresh_ordermodel',
            name='e_user',
        ),
        migrations.RemoveField(
            model_name='jewel_ordermodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='jewel_ordermodel',
            name='e_user',
        ),
        migrations.RemoveField(
            model_name='pharmacy_ordermodel',
            name='business',
        ),
        migrations.RemoveField(
            model_name='pharmacy_ordermodel',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='pharmacy_ordermodel',
            name='e_user',
        ),
        migrations.DeleteModel(
            name='daily_ordermodel',
        ),
        migrations.DeleteModel(
            name='dorigin_ordermodel',
        ),
        migrations.DeleteModel(
            name='food_ordermodel',
        ),
        migrations.DeleteModel(
            name='fresh_ordermodel',
        ),
        migrations.DeleteModel(
            name='jewel_ordermodel',
        ),
        migrations.DeleteModel(
            name='pharmacy_ordermodel',
        ),
    ]
