# Generated by Django 4.0.4 on 2024-04-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_delete_shop_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Ordermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField(null=True)),
                ('track_id', models.TextField(null=True)),
                ('quantity', models.TextField(null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('total_amount', models.TextField(null=True)),
                ('status', models.TextField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('payment_status', models.TextField(null=True)),
                ('delivery_type', models.TextField(null=True)),
                ('category_data', models.TextField(null=True)),
                ('d_original_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.d_original_productsmodel')),
                ('dmio_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dmio_productsmodel')),
                ('end_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel')),
                ('food_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.food_productsmodel')),
                ('freshcut_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fresh_productsmodel')),
                ('jewel_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jewel_productsmodel')),
                ('pharmacy_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_productsmodel')),
                ('shop_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel')),
            ],
        ),
    ]
