# Generated by Django 4.0.4 on 2024-04-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_product_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_usermodel',
            name='address_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='temp_address',
            field=models.JSONField(null=True),
        ),
    ]
