# Generated by Django 4.0.4 on 2024-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_end_usermodel_address_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_original_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dmio_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='food_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fresh_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='jewel_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shop_productsmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='d_original_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dmio_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='food_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fresh_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='jewel_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='shop_productsmodel',
            name='status',
            field=models.TextField(default=False, null=True),
        ),
    ]
