# Generated by Django 4.0.4 on 2024-04-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_d_original_productsmodel_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='shop_id',
            field=models.TextField(null=True),
        ),
    ]
