# Generated by Django 4.0.4 on 2024-04-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_product_ordermodel_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='product_id',
            field=models.TextField(null=True),
        ),
    ]
