# Generated by Django 4.0.4 on 2024-04-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_d_originalmodel_date_alter_dailymio_model_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_originalmodel',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='jewellerymodel',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='shoppingmodel',
            name='hub',
        ),
    ]
