# Generated by Django 4.0.4 on 2024-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_d_originalmodel_hub_remove_jewellerymodel_hub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_originalmodel',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewellerymodel',
            name='region',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shoppingmodel',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
