# Generated by Django 4.0.4 on 2024-04-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_d_originalmodel_region_jewellerymodel_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='d_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='dmio_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='fresh_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='jewel_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='pharm_id',
        ),
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='shop_id',
        ),
    ]
