# Generated by Django 4.0.4 on 2024-04-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_product_ordermodel_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='d_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.d_originalmodel'),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='dmio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dailymio_model'),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='food_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.foodmodel'),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='fresh_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.freshcutsmodel'),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='jewel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jewellerymodel'),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='pharm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_model'),
        ),
    ]
