# Generated by Django 4.0.4 on 2024-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_product_ordermodel_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
