# Generated by Django 4.0.4 on 2024-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_delivery_model_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_original_productsmodel',
            name='district',
            field=models.TextField(null=True),
        ),
    ]
