# Generated by Django 4.0.4 on 2024-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_product_ordermodel_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='submit_issues',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='upload_issues',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='payment_type',
            field=models.TextField(null=True),
        ),
    ]
