# Generated by Django 4.0.4 on 2024-04-13 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_delivery_model_submit_issues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='qty',
        ),
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='latitude',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='longitude',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 20), null=True),
        ),
    ]
