# Generated by Django 4.0.4 on 2024-04-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_carts_qty_carts_total_end_usermodel_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.TextField(null=True),
        ),
    ]
