# Generated by Django 4.0.4 on 2024-04-13 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_carts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='deliveryperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model'),
        ),
    ]
