# Generated by Django 4.0.4 on 2024-04-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_product_ordermodel_deliveryperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliverylogintable_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_date', models.DateField(auto_now_add=True, null=True)),
                ('login_time', models.TimeField(auto_now_add=True, null=True)),
                ('logout_time', models.TimeField(null=True)),
                ('deliveryperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.delivery_model')),
            ],
        ),
    ]
