# Generated by Django 4.0.4 on 2024-04-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_deliverylogintable_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylogintable_model',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
