# Generated by Django 4.0.4 on 2024-04-14 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_product_ordermodel_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_ordermodel',
            name='delivery_address',
        ),
    ]
