# Generated by Django 4.0.4 on 2024-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_remove_product_ordermodel_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='delivery_address',
            field=models.JSONField(null=True),
        ),
    ]
