# Generated by Django 4.0.4 on 2024-04-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_product_ordermodel_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='whishlistmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('d_origin_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.d_original_productsmodel')),
                ('dailymio_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dmio_productsmodel')),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.food_productsmodel')),
                ('freshcut_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fresh_productsmodel')),
                ('jewel_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jewel_productsmodel')),
                ('pharmacy_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_productsmodel')),
                ('shop_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel')),
            ],
        ),
    ]
