# Generated by Django 4.0.4 on 2024-04-14 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_whishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='category',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='d_origin_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.d_original_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='dailymio_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dmio_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='food_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.food_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='freshcut_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fresh_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='jewel_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jewel_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='pharmacy_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel'),
        ),
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 22), null=True),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='d_origin_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.d_original_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='dailymio_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dmio_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='food_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.food_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='freshcut_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fresh_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='jewel_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jewel_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='pharmacy_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel'),
        ),
        migrations.AlterField(
            model_name='whishlistmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
    ]
