# Generated by Django 4.0.4 on 2024-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_carts_category_alter_carts_d_origin_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
