# Generated by Django 4.0.4 on 2024-04-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_carts_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='comment',
        ),
        migrations.AddField(
            model_name='whishlistmodel',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
