# Generated by Django 4.0.4 on 2024-04-16 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_reviews_comment_whishlistmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d_originalmodel',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='dailymio_model',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='foodmodel',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='freshcutsmodel',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='jewellerymodel',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='pharmacy_model',
            name='pin_number',
        ),
        migrations.RemoveField(
            model_name='shoppingmodel',
            name='pin_number',
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 23), null=True),
        ),
    ]
