# Generated by Django 4.0.4 on 2024-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_d_originalmodel_pincode_dailymio_model_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
