# Generated by Django 4.0.4 on 2024-04-17 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_delivery_model_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='uid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 24), null=True),
        ),
    ]
