# Generated by Django 4.0.4 on 2024-04-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_carts_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='uid',
        ),
    ]
