# Generated by Django 4.0.4 on 2024-04-17 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_reviews_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='used_productsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField(null=True)),
                ('status', models.TextField(default=False, null=True)),
                ('category', models.TextField(null=True)),
                ('subcategory', models.TextField(null=True)),
                ('product', models.JSONField(null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 25), null=True),
        ),
    ]
