# Generated by Django 4.0.4 on 2024-04-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_used_productsmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='d_origin_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.d_original_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='dailymio_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dmio_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='food_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.food_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='freshcut_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fresh_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='jewel_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.jewel_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pharmacy_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='shop_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop_productsmodel'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.end_usermodel'),
        ),
    ]
