# Generated by Django 4.0.4 on 2024-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_product_ordermodel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='emergency',
            field=models.TextField(null=True),
        ),
    ]
