# Generated by Django 4.0.4 on 2024-04-19 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_product_ordermodel_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='emergency_optional',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='reason_optional',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 27), null=True),
        ),
    ]
