# Generated by Django 4.0.4 on 2024-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_product_ordermodel_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
