# Generated by Django 4.0.4 on 2024-04-21 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_product_ordermodel_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylogintable_model',
            name='distance',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 28), null=True),
        ),
    ]
