# Generated by Django 4.0.4 on 2024-04-22 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_deliverylogintable_model_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylogintable_model',
            name='delivery_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 29), null=True),
        ),
    ]
