# Generated by Django 4.0.4 on 2024-04-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_deliverylogintable_model_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
