# Generated by Django 4.0.4 on 2024-04-23 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_product_ordermodel_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylogintable_model',
            name='distance',
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 4, 30), null=True),
        ),
    ]
