# Generated by Django 4.0.4 on 2024-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_remove_deliverylogintable_model_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='distance',
            field=models.TextField(null=True),
        ),
    ]
