# Generated by Django 4.0.4 on 2024-04-24 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_product_ordermodel_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='device_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 1), null=True),
        ),
    ]
