# Generated by Django 4.0.4 on 2024-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_delivery_model_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylogintable_model',
            name='delivery_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deliverylogintable_model',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
