# Generated by Django 4.0.4 on 2024-04-25 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_deliverylogintable_model_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='verified',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 2), null=True),
        ),
    ]
