# Generated by Django 4.0.4 on 2024-04-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_delivery_model_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_model',
            name='verified',
            field=models.TextField(default=False, null=True),
        ),
    ]
