# Generated by Django 4.0.4 on 2024-04-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_delivery_model_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='user_otp',
            field=models.IntegerField(null=True),
        ),
    ]
