# Generated by Django 4.0.4 on 2024-04-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_delivery_model_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_model',
            name='verified',
        ),
    ]
