# Generated by Django 4.0.4 on 2024-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_remove_delivery_model_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_original_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dmio_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='fresh_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jewel_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shop_productsmodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
    ]
