# Generated by Django 4.0.4 on 2024-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_d_original_productsmodel_business_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='business_pickup',
            field=models.BooleanField(null=True),
        ),
    ]
