# Generated by Django 4.0.4 on 2024-04-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_product_ordermodel_business_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='device_id',
            field=models.JSONField(null=True),
        ),
    ]
