# Generated by Django 4.0.4 on 2024-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_businessmodel_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='order_total',
            field=models.TextField(null=True),
        ),
    ]
