# Generated by Django 4.0.4 on 2024-04-25 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_product_ordermodel_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='business_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 3), null=True),
        ),
    ]
