# Generated by Django 4.0.4 on 2024-04-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_product_ordermodel_business_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='incentive',
            field=models.TextField(null=True),
        ),
    ]
