# Generated by Django 4.0.4 on 2024-04-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_product_ordermodel_incentive'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='ready_to_pick_up',
            field=models.BooleanField(default=0),
        ),
    ]
