# Generated by Django 4.0.4 on 2024-04-27 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_remove_product_ordermodel_business_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='end_usermodel',
            name='temp_address',
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 4), null=True),
        ),
    ]
