# Generated by Django 4.0.4 on 2024-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_remove_end_usermodel_temp_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='ship_to_other_region',
            field=models.TextField(null=True),
        ),
    ]
