# Generated by Django 4.0.4 on 2024-04-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0136_delivery_model_has_withdrawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_id', models.TextField(null=True)),
                ('sender_id', models.TextField(null=True)),
                ('notify_message', models.TextField(null=True)),
                ('recever_id', models.TextField(null=True)),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('notify_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
