# Generated by Django 4.0.4 on 2024-04-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='notification_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='delivery_model',
            name='notification_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='end_usermodel',
            name='notification_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
