# Generated by Django 4.0.4 on 2024-04-29 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_businessmodel_notification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='product_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 6), null=True),
        ),
    ]
