# Generated by Django 4.0.4 on 2024-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_reviews_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='floating_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_ordermodel',
            name='float_cash',
            field=models.TextField(null=True),
        ),
    ]
