# Generated by Django 4.0.4 on 2024-04-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_delivery_model_floating_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_model',
            name='float_amount',
            field=models.TextField(null=True),
        ),
    ]
