# Generated by Django 4.0.4 on 2024-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_delivery_model_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_ordermodel',
            name='admin_commission_amount',
            field=models.TextField(null=True),
        ),
    ]
