# Generated by Django 5.0 on 2024-04-30 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_d_original_productsmodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_productsmodel',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
