# Generated by Django 5.0 on 2024-05-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0146_alter_d_original_productsmodel_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 8), null=True),
        ),
    ]
