# Generated by Django 5.0 on 2024-05-02 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0147_alter_product_ordermodel_expected_deliverydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_ordermodel',
            name='expected_deliverydate',
            field=models.DateField(default=datetime.date(2024, 5, 9), null=True),
        ),
    ]
