# Generated by Django 5.0 on 2024-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_product_return_out_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_return',
            name='out_of_delivery',
            field=models.TextField(default=0),
        ),
    ]
