# Generated by Django 5.0 on 2024-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_alter_product_return_out_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_return',
            name='out_of_delivery',
            field=models.TextField(null=True),
        ),
    ]
