            # 'phone_number':request.data'phone_number'],
            # 'wp_number': request.data['wp_number'],
            # 'email': request.data["email"],
            # 'aadhar_number':request.data['aadhar_number'],                    
            # 'driving_licensenum':request.data['driving_licensenum'],
            # 'pan_number':request.data['pan_number'],                    
            # 'profile_picture':profile_picturepaths,
            # 'bank_name':request.data['bank_name'],
            # 'acc_number':request.data['acc_number'],
            # 'name_asper_passbook':request.data['name_asper_passbook'],
            # 'ifsc_code':request.data['ifsc_code'],
            # 'bank_passbok_pic':bank_passbok_pic_paths,
            # 'aadhar_pic':aadhar_pic_paths,
            # 'pan_pic':pan_pic_paths,
            # 'drlicence_pic':drlicence_pic_paths,
            # 'delivery_type':request.data['delivery_type'],